apiVersion: v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metaData:
      labels:
        app: nginx
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
