apiVersion: v1
kind: Deployment
metadata:
  name: deplname
  labels:
    app: selector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selector
  template:
    metaData:
      labels:
        app: selector
    spec:
      containers:
        - name: contname
          image: contimage
          ports:
            - containerPort: 80
